---
  email_config:
    smtp_server: "smtp.XXXXX.XXXX"
    port: 587 
    login: "XXXX@XXXXX.XXXX"
    password: "XXXXXXXXXX"
    sender_email: "XXXX@XXXXX.XXXX"
    receiver_email: "XXXX@XXXXX.XXXX"
  update_config:
    update_time: "0:00"
    mtl_data: "https://data.montreal.ca/dataset/\
      05a9e718-6810-4e73-8bb9-5955efeb91a0/resource/\
      7f939a08-be8a-45e1-b208-d8744dca8fc6/download/violations.csv"